# Generated by Django 5.1 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarbershopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Barbearia Francisco",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        default="5545999417111", max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict, verbose_name="Horário de Funcionamento"
                    ),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração da Barbearia",
                "verbose_name_plural": "Configurações da Barbearia",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Nota",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Comentário")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Aprovado"),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("time", models.TimeField(verbose_name="Horário")),
                (
                    "notified",
                    models.BooleanField(default=False, verbose_name="Notificado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Lista de Espera",
                "verbose_name_plural": "Lista de Espera",
                "ordering": ["date", "time"],
            },
        ),
    ]
