# Generated by Django 5.1 on 2025-11-12 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbeiros", "0003_barbeiro_barbeiros_b_active_c9b9b7_idx_and_more"),
        ("core", "0001_initial"),
        ("servicos", "0003_servico_badge_servico_combo_services_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criar"),
                            ("UPDATE", "Atualizar"),
                            ("DELETE", "Deletar"),
                            ("INSERT", "Inserir"),
                        ],
                        max_length=10,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.CharField(blank=True, max_length=100, null=True)),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="waitinglist",
            name="notified",
        ),
        migrations.RemoveField(
            model_name="waitinglist",
            name="preferred_time",
        ),
        migrations.AddField(
            model_name="waitinglist",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitinglist",
            name="preferred_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitinglist",
            name="preferred_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitinglist",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Aguardando"),
                    ("notified", "Notificado"),
                    ("contacted", "Contactado"),
                    ("scheduled", "Agendado"),
                    ("cancelled", "Cancelado"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglist",
            index=models.Index(
                fields=["status", "-created_at"], name="core_waitin_status_dc75e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglist",
            index=models.Index(
                fields=["preferred_date"], name="core_waitin_preferr_5c6de8_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="core_auditl_created_1a76fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["table_name"], name="core_auditl_table_n_4a8950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="core_auditl_action_d9fb24_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="core_auditl_user_id_2ff9b7_idx"),
        ),
    ]
