# Generated by Django 5.1 on 2025-11-12 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0003_initial"),
        ("barbeiros", "0003_barbeiro_barbeiros_b_active_c9b9b7_idx_and_more"),
        ("core", "0002_auditlog_remove_waitinglist_notified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(default=dict, verbose_name="Dados de Contexto"),
                ),
                (
                    "last_summary",
                    models.TextField(blank=True, verbose_name="Último Resumo"),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, verbose_name="Contagem de Mensagens"
                    ),
                ),
                (
                    "last_user_message",
                    models.TextField(
                        blank=True, verbose_name="Última Mensagem do Usuário"
                    ),
                ),
                (
                    "last_ai_response",
                    models.TextField(blank=True, verbose_name="Última Resposta da IA"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="agendamentos.agendamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contexto de Conversa IA",
                "verbose_name_plural": "Contextos de Conversa IA",
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="IA Habilitada"),
                ),
                (
                    "personality",
                    models.CharField(
                        choices=[
                            ("friendly", "Amigável"),
                            ("professional", "Profissional"),
                        ],
                        default="friendly",
                        max_length=20,
                        verbose_name="Personalidade",
                    ),
                ),
                (
                    "custom_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instruções específicas para personalizar o comportamento da IA",
                        verbose_name="Instruções Personalizadas",
                    ),
                ),
                (
                    "max_message_length",
                    models.IntegerField(
                        default=1000, verbose_name="Tamanho Máximo de Mensagem"
                    ),
                ),
                (
                    "response_time_seconds",
                    models.IntegerField(
                        default=5, verbose_name="Tempo de Resposta (segundos)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="barbeiros.barbeiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de IA",
                "verbose_name_plural": "Configurações de IA",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "is_ai_response",
                    models.BooleanField(default=False, verbose_name="Resposta da IA"),
                ),
                (
                    "requires_human_attention",
                    models.BooleanField(
                        default=False, verbose_name="Requer Atenção Humana"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lida em"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="agendamentos.agendamento",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Chat",
                "verbose_name_plural": "Mensagens de Chat",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["appointment", "created_at"],
                        name="core_chatme_appoint_eb6d4b_idx",
                    ),
                    models.Index(
                        fields=["requires_human_attention"],
                        name="core_chatme_require_0f88d5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Confirmação"),
                            ("reminder", "Lembrete"),
                            ("cancellation", "Cancelamento"),
                            ("rescheduled", "Reagendamento"),
                            ("completed", "Concluído"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(max_length=200, verbose_name="Destinatário"),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("delivered", "Entregue"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da API externa (Twilio, etc)",
                        max_length=200,
                        verbose_name="ID Externo",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entregue em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="agendamentos.agendamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_notifi_status_58cb4f_idx",
                    ),
                    models.Index(
                        fields=["appointment"], name="core_notifi_appoint_5f4fa3_idx"
                    ),
                    models.Index(
                        fields=["type", "channel"], name="core_notifi_type_a6f2b5_idx"
                    ),
                ],
            },
        ),
    ]
