# Generated by Django 5.1 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barbeiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Especialidade"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "working_hours",
                    models.JSONField(
                        default=dict,
                        help_text='Ex: {"monday": {"active": true, "start": "08:00", "end": "18:00"}}',
                        verbose_name="Horários de Trabalho",
                    ),
                ),
                (
                    "days_off",
                    models.JSONField(
                        default=list,
                        help_text='Lista de datas: ["2024-12-25", "2024-12-31"]',
                        verbose_name="Dias de Folga",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Barbeiro",
                "verbose_name_plural": "Barbeiros",
                "ordering": ["name"],
            },
        ),
    ]
