# Generated by Django 5.1 on 2025-11-10 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbeiros", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="barbeiro",
            index=models.Index(fields=["active"], name="barbeiros_b_active_c9b9b7_idx"),
        ),
        migrations.AddIndex(
            model_name="barbeiro",
            index=models.Index(fields=["name"], name="barbeiros_b_name_52fd7b_idx"),
        ),
    ]
