# Generated by Django 5.1 on 2025-11-28 00:17
# Modified to handle existing 'barbers' table

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db import connection


def apply_migration_0004(apps, schema_editor):
    """
    Aplica todas as mudanças da migração 0004 de forma condicional.
    Verifica o estado atual do banco e aplica apenas o que for necessário.
    """
    with connection.cursor() as cursor:
        # Verificar se barbers já existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'barbers'
        """)
        barbers_exists = cursor.fetchone()[0] > 0
        
        # Verificar se barbeiros_barbeiro existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'barbeiros_barbeiro'
        """)
        barbeiros_barbeiro_exists = cursor.fetchone()[0] > 0
        
        target_table = 'barbers' if barbers_exists else 'barbeiros_barbeiro'
        
        if barbers_exists and barbeiros_barbeiro_exists:
            # Ambas existem - remover a antiga (barbeiros_barbeiro está vazia)
            print("[INFO] Tabela 'barbers' já existe. Removendo tabela antiga 'barbeiros_barbeiro'...")
            cursor.execute('DROP TABLE IF EXISTS "barbeiros_barbeiro" CASCADE')
        elif barbeiros_barbeiro_exists and not barbers_exists:
            # Apenas barbeiros_barbeiro existe - renomear
            print("[INFO] Renomeando 'barbeiros_barbeiro' para 'barbers'...")
            cursor.execute('ALTER TABLE "barbeiros_barbeiro" RENAME TO "barbers"')
            target_table = 'barbers'
        
        # Verificar e criar/renomear índices
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE schemaname = 'public' 
            AND tablename = %s
        """, [target_table])
        existing_indexes = [row[0] for row in cursor.fetchall()]
        
        # Índice 1: active
        if 'barbeiros_b_active_c9b9b7_idx' in existing_indexes:
            if 'barbers_active_f688d1_idx' not in existing_indexes:
                print("[INFO] Renomeando índice 'barbeiros_b_active_c9b9b7_idx'...")
                cursor.execute('ALTER INDEX "barbeiros_b_active_c9b9b7_idx" RENAME TO "barbers_active_f688d1_idx"')
        elif 'barbers_active_f688d1_idx' not in existing_indexes:
            print("[INFO] Criando índice 'barbers_active_f688d1_idx'...")
            cursor.execute('CREATE INDEX IF NOT EXISTS "barbers_active_f688d1_idx" ON "barbers" ("active")')
        
        # Índice 2: name
        if 'barbeiros_b_name_52fd7b_idx' in existing_indexes:
            if 'barbers_name_1a1a6e_idx' not in existing_indexes:
                print("[INFO] Renomeando índice 'barbeiros_b_name_52fd7b_idx'...")
                cursor.execute('ALTER INDEX "barbeiros_b_name_52fd7b_idx" RENAME TO "barbers_name_1a1a6e_idx"')
        elif 'barbers_name_1a1a6e_idx' not in existing_indexes:
            print("[INFO] Criando índice 'barbers_name_1a1a6e_idx'...")
            cursor.execute('CREATE INDEX IF NOT EXISTS "barbers_name_1a1a6e_idx" ON "barbers" ("name")')
        
        # Remover/adicionar campos se a tabela barbers existir
        if barbers_exists:
            print("[INFO] Verificando campos na tabela 'barbers'...")
            
            # Verificar quais colunas existem
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'barbers' 
                AND table_schema = 'public'
            """)
            existing_columns = [row[0] for row in cursor.fetchall()]
            
            # Remover campo days_off se existir
            if 'days_off' in existing_columns:
                print("[INFO] Removendo campo 'days_off'...")
                # Verificar se há views que dependem desta coluna
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM pg_views 
                    WHERE viewname = 'barbers_public' 
                    AND schemaname = 'public'
                """)
                view_exists = cursor.fetchone()[0] > 0
                if view_exists:
                    print("[INFO] Removendo view 'barbers_public' que depende de 'days_off'...")
                    cursor.execute('DROP VIEW IF EXISTS "barbers_public" CASCADE')
                cursor.execute('ALTER TABLE "barbers" DROP COLUMN IF EXISTS "days_off" CASCADE')
            
            # Adicionar campo photo_url se não existir
            if 'photo_url' not in existing_columns:
                print("[INFO] Adicionando campo 'photo_url'...")
                cursor.execute('ALTER TABLE "barbers" ADD COLUMN "photo_url" VARCHAR(200)')
        
        print("[OK] Migração 0004 aplicada com sucesso!")


def reverse_migration_0004(apps, schema_editor):
    """
    Reversão não implementada - muito complexa
    """
    raise migrations.IrreversibleMigration(
        "Reversão da migração 0004 não é suportada."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("barbeiros", "0003_barbeiro_barbeiros_b_active_c9b9b7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(apply_migration_0004, reverse_migration_0004),
        # Operações de estado para manter o Django sincronizado (não executam no banco)
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL - operações já foram feitas na função Python
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="barbeiro",
                    new_name="barbers_active_f688d1_idx",
                    old_name="barbeiros_b_active_c9b9b7_idx",
                ),
                migrations.RenameIndex(
                    model_name="barbeiro",
                    new_name="barbers_name_1a1a6e_idx",
                    old_name="barbeiros_b_name_52fd7b_idx",
                ),
                migrations.RemoveField(
                    model_name="barbeiro",
                    name="days_off",
                ),
                migrations.AddField(
                    model_name="barbeiro",
                    name="photo_url",
                    field=models.URLField(blank=True, null=True, verbose_name="URL da Foto"),
                ),
                migrations.AlterField(
                    model_name="barbeiro",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                migrations.AlterField(
                    model_name="barbeiro",
                    name="user",
                    field=models.OneToOneField(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barbeiro_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name="barbeiro",
                    name="working_hours",
                    field=models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex: {"monday": {"active": true, "start": "08:00", "end": "18:00"}}',
                        null=True,
                        verbose_name="Horários de Trabalho",
                    ),
                ),
                migrations.AlterModelTable(
                    name="barbeiro",
                    table="barbers",
                ),
            ],
        ),
    ]
