# Generated by Django 5.1 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Desconto"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Porcentagem"),
                            ("fixed", "Valor Fixo"),
                        ],
                        default="percentage",
                        max_length=10,
                        verbose_name="Tipo de Desconto",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Expiração"
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        default=0,
                        help_text="0 para ilimitado",
                        verbose_name="Usos Máximos",
                    ),
                ),
                (
                    "current_uses",
                    models.IntegerField(default=0, verbose_name="Usos Atuais"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cupom",
                "verbose_name_plural": "Cupons",
                "ordering": ["-created_at"],
            },
        ),
    ]
