# Generated by Django 5.1 on 2025-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupons", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cupom",
            index=models.Index(fields=["code"], name="cupons_cupo_code_8127ef_idx"),
        ),
        migrations.AddIndex(
            model_name="cupom",
            index=models.Index(
                fields=["active", "expiry_date"], name="cupons_cupo_active_94e74d_idx"
            ),
        ),
    ]
