# Generated by Django 5.1 on 2025-11-28 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupons", "0002_cupom_cupons_cupo_code_8127ef_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cupom",
            new_name="coupons_code_94ae53_idx",
            old_name="cupons_cupo_code_8127ef_idx",
        ),
        migrations.RenameIndex(
            model_name="cupom",
            new_name="coupons_active_d86f8d_idx",
            old_name="cupons_cupo_active_94e74d_idx",
        ),
        migrations.AlterField(
            model_name="cupom",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="cupom",
            table="coupons",
        ),
    ]
