# Generated by Django 5.1 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="Data")),
                ("appointment_time", models.TimeField(verbose_name="Horário")),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Nome do Cliente"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Telefone do Cliente"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email do Cliente"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("credit", "Cartão de Crédito"),
                            ("debit", "Cartão de Débito"),
                            ("pix", "PIX"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código do Cupom"
                    ),
                ),
                (
                    "promotion_applied",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Promoção Aplicada"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelado em"
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(blank=True, verbose_name="Foto do Resultado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
    ]
