# Generated by Django 5.1 on 2025-11-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("barbeiros", "0001_initial"),
        ("cupons", "0001_initial"),
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="barber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="barbeiros.barbeiro",
                verbose_name="Barbeiro",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cupons.cupom",
                verbose_name="Cupom",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="servicos.servico",
                verbose_name="Serviço",
            ),
        ),
    ]
