# Generated by Django 5.1 on 2025-11-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["appointment_date", "appointment_time"],
                name="agendamento_appoint_c2c1ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(fields=["status"], name="agendamento_status_24d1a6_idx"),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(fields=["user"], name="agendamento_user_id_017d64_idx"),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["barber"], name="agendamento_barber__f27fa6_idx"
            ),
        ),
    ]
