# Generated by Django 5.1 on 2025-11-26 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0003_initial"),
        ("barbeiros", "0003_barbeiro_barbeiros_b_active_c9b9b7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="barbeiros.barbeiro",
                verbose_name="Barbeiro",
            ),
        ),
    ]
