# Generated by Django 5.1 on 2025-11-28 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0004_alter_agendamento_barber"),
        (
            "barbeiros",
            "0004_rename_barbeiros_b_active_c9b9b7_idx_barbers_active_f688d1_idx_and_more",
        ),
        (
            "servicos",
            "0004_rename_servicos_se_active_859940_idx_services_active_f49dbe_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agendamento",
            name="agendamento_user_id_017d64_idx",
        ),
        migrations.RemoveIndex(
            model_name="agendamento",
            name="agendamento_barber__f27fa6_idx",
        ),
        migrations.RenameIndex(
            model_name="agendamento",
            new_name="appointment_appoint_f2c2fb_idx",
            old_name="agendamento_appoint_c2c1ab_idx",
        ),
        migrations.RenameIndex(
            model_name="agendamento",
            new_name="appointment_status_9fecd6_idx",
            old_name="agendamento_status_24d1a6_idx",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="photo_url",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="promotion_applied",
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                db_column="barber_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="barbeiros.barbeiro",
                verbose_name="Barbeiro",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                db_column="coupon_code",
                max_length=20,
                null=True,
                verbose_name="Código do Cupom",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="service",
            field=models.ForeignKey(
                db_column="service_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="servicos.servico",
                verbose_name="Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmado"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["user_id"], name="appointment_user_id_eea5b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["barber_id"], name="appointment_barber__b55842_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="agendamento",
            table="appointments",
        ),
    ]
