# Generated by Django 5.1 on 2025-11-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["active", "category"], name="servicos_se_active_859940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(fields=["name"], name="servicos_se_name_707a5d_idx"),
        ),
    ]
