# Generated by Django 5.1 on 2025-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_servico_servicos_se_active_859940_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="badge",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Badge/Destaque"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="combo_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="combos",
                to="servicos.servico",
                verbose_name="Serviços do Combo",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Características"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="URL da Imagem"),
        ),
        migrations.AddField(
            model_name="servico",
            name="is_combo",
            field=models.BooleanField(default=False, verbose_name="É um Combo?"),
        ),
        migrations.AddField(
            model_name="servico",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Preço Original",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="category",
            field=models.CharField(
                choices=[
                    ("haircut", "Corte"),
                    ("beard", "Barba"),
                    ("treatment", "Tratamento"),
                    ("combo", "Combo"),
                ],
                default="haircut",
                max_length=15,
                verbose_name="Categoria",
            ),
        ),
    ]
