# Generated by Django 5.1 on 2025-11-28 00:17
# Modified to handle existing 'services' table

import uuid
from django.db import migrations, models
from django.db import connection


def apply_migration_0004(apps, schema_editor):
    """
    Aplica todas as mudanças da migração 0004 de forma condicional.
    Verifica o estado atual do banco e aplica apenas o que for necessário.
    """
    with connection.cursor() as cursor:
        # Verificar se services já existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'services'
        """)
        services_exists = cursor.fetchone()[0] > 0
        
        # Verificar se servicos_servico existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'servicos_servico'
        """)
        servicos_servico_exists = cursor.fetchone()[0] > 0
        
        target_table = 'services' if services_exists else 'servicos_servico'
        
        if services_exists and servicos_servico_exists:
            # Ambas existem - remover a antiga (servicos_servico está vazia)
            print("[INFO] Tabela 'services' já existe. Removendo tabela antiga 'servicos_servico'...")
            cursor.execute('DROP TABLE IF EXISTS "servicos_servico" CASCADE')
        elif servicos_servico_exists and not services_exists:
            # Apenas servicos_servico existe - renomear
            print("[INFO] Renomeando 'servicos_servico' para 'services'...")
            cursor.execute('ALTER TABLE "servicos_servico" RENAME TO "services"')
            target_table = 'services'
        
        # Verificar e criar/renomear índices
        cursor.execute("""
            SELECT indexname 
            FROM pg_indexes 
            WHERE schemaname = 'public' 
            AND tablename = %s
        """, [target_table])
        existing_indexes = [row[0] for row in cursor.fetchall()]
        
        # Índice 1: active + category
        if 'servicos_se_active_859940_idx' in existing_indexes:
            if 'services_active_f49dbe_idx' not in existing_indexes:
                print("[INFO] Renomeando índice 'servicos_se_active_859940_idx'...")
                cursor.execute('ALTER INDEX "servicos_se_active_859940_idx" RENAME TO "services_active_f49dbe_idx"')
        elif 'services_active_f49dbe_idx' not in existing_indexes:
            print("[INFO] Criando índice 'services_active_f49dbe_idx'...")
            cursor.execute('CREATE INDEX IF NOT EXISTS "services_active_f49dbe_idx" ON "services" ("active", "category")')
        
        # Índice 2: name
        if 'servicos_se_name_707a5d_idx' in existing_indexes:
            if 'services_name_a79f61_idx' not in existing_indexes:
                print("[INFO] Renomeando índice 'servicos_se_name_707a5d_idx'...")
                cursor.execute('ALTER INDEX "servicos_se_name_707a5d_idx" RENAME TO "services_name_a79f61_idx"')
        elif 'services_name_a79f61_idx' not in existing_indexes:
            print("[INFO] Criando índice 'services_name_a79f61_idx'...")
            cursor.execute('CREATE INDEX IF NOT EXISTS "services_name_a79f61_idx" ON "services" ("name")')
        
        # Remover campos se a tabela services existir
        if services_exists:
            print("[INFO] Verificando campos na tabela 'services'...")
            
            # Verificar quais colunas existem
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name = 'services' 
                AND table_schema = 'public'
            """)
            existing_columns = [row[0] for row in cursor.fetchall()]
            
            # Remover campos que não devem existir
            fields_to_remove = ['badge', 'combo_services', 'features', 'is_combo', 'original_price']
            for field in fields_to_remove:
                if field in existing_columns:
                    print(f"[INFO] Removendo campo '{field}'...")
                    cursor.execute(f'ALTER TABLE "services" DROP COLUMN IF EXISTS "{field}"')
            
            # Adicionar campo is_active se não existir
            if 'is_active' not in existing_columns:
                print("[INFO] Adicionando campo 'is_active'...")
                cursor.execute('ALTER TABLE "services" ADD COLUMN "is_active" BOOLEAN DEFAULT TRUE')
            
            # Alterar campo active para permitir null
            if 'active' in existing_columns:
                cursor.execute('ALTER TABLE "services" ALTER COLUMN "active" DROP NOT NULL')
            
            # Alterar campo image_url para permitir null
            if 'image_url' in existing_columns:
                cursor.execute('ALTER TABLE "services" ALTER COLUMN "image_url" DROP NOT NULL')
        
        print("[OK] Migração 0004 aplicada com sucesso!")


def reverse_migration_0004(apps, schema_editor):
    """
    Reversão não implementada - muito complexa
    """
    raise migrations.IrreversibleMigration(
        "Reversão da migração 0004 não é suportada."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0003_servico_badge_servico_combo_services_and_more"),
    ]

    operations = [
        migrations.RunPython(apply_migration_0004, reverse_migration_0004),
        # Operações de estado para manter o Django sincronizado (não executam no banco)
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL - operações já foram feitas na função Python
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="servico",
                    new_name="services_active_f49dbe_idx",
                    old_name="servicos_se_active_859940_idx",
                ),
                migrations.RenameIndex(
                    model_name="servico",
                    new_name="services_name_a79f61_idx",
                    old_name="servicos_se_name_707a5d_idx",
                ),
                migrations.RemoveField(
                    model_name="servico",
                    name="badge",
                ),
                migrations.RemoveField(
                    model_name="servico",
                    name="combo_services",
                ),
                migrations.RemoveField(
                    model_name="servico",
                    name="features",
                ),
                migrations.RemoveField(
                    model_name="servico",
                    name="is_combo",
                ),
                migrations.RemoveField(
                    model_name="servico",
                    name="original_price",
                ),
                migrations.AddField(
                    model_name="servico",
                    name="is_active",
                    field=models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Ativo"
                    ),
                ),
                migrations.AlterField(
                    model_name="servico",
                    name="active",
                    field=models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Ativo"
                    ),
                ),
                migrations.AlterField(
                    model_name="servico",
                    name="image_url",
                    field=models.URLField(blank=True, null=True, verbose_name="URL da Imagem"),
                ),
                migrations.AlterModelTable(
                    name="servico",
                    table="services",
                ),
            ],
        ),
    ]
