# Generated by Django 5.1 on 2025-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Criação"),
                            ("update", "Atualização"),
                            ("delete", "Exclusão"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=10,
                        verbose_name="Ação",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID do Objeto"
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="Detalhes")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("first_visit", "Primeira Visita"),
                            ("happy_hour", "Happy Hour"),
                            ("combo", "Combo"),
                            ("loyalty", "Fidelidade"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Porcentagem"),
                            ("fixed", "Valor Fixo"),
                        ],
                        default="percentage",
                        max_length=10,
                        verbose_name="Tipo de Desconto",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do Desconto",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text='Ex: {"days_of_week": [0, 6], "time_start": "08:00", "time_end": "12:00"}',
                        verbose_name="Condições",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Data de Fim"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Promoção",
                "verbose_name_plural": "Promoções",
                "ordering": ["-created_at"],
            },
        ),
    ]
